name: HelloWorld
version: 1.2.2
author: Akariiinnn
main: me.akariiinnn.helloworld.Main
description: My first Minecraft spigot plugin
api-version: 1.13

commands:
  hello:
    aliases: [hi]
    description: this is the hello command
  burn:
    aliases: [setonfire]
    description: sets the sender on fire
  fly:
    aliases: [superman]
    description: makes you fly
  craft:
    description: opens a crafting table
  horse:
    aliases: [epona]
    description: summons a horse that you can ride
  enderchest:
    aliases: [ec]
    descritption: opens your enderchest
  oops:
    aliases: [nuke]
    description: spawns TNT up in the sky