name: HelloWorld
version: 1.2
author: Akariiinnn
main: me.akariiinnn.helloworld.Main
description: My first Minecraft spigot plugin
api-version: 1.13

commands:
  hello:
    aliases: [hi]
    description: this is the hello command
  burn:
    aliases: [setonfire]
    description: sets the sender on fire
  fly:
    aliases: [superman]
    description: makes you fly